apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  generators:
    - directory:
        repoURL: https://github.com/rocklobster1618/cicd-sockshop.git
        targetRevision: main
        path: "workload/*"     # each subfolder becomes an app
  template:
    metadata:
      name: "{{path.basename}}"
      namespace: argocd
    spec:
      project: workload
      source:
        repoURL: https://github.com/rocklobster1618/cicd-sockshop.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true