global:
    image:
        tag: "" 

crds:
    install: true

applicationSet:
    enabled: true

dex:
    enabled: false

server:
    extraArgs:
    - --insecure # For quick access while developing; use 'kubectl port-forward' in the interim
    
    service:
        type: ClusterIP # To be replaced Ingress and TLS later.

controller:
    resources:
        requests:
            cpu: 100m
            memory: 256Mi
    
repoServer:
    resources:
        requests:
            cpu: 100m
            memory: 256Mi
    
redis:
    resources:
        requests:
            cpu: 50m
            memory: 64Mi

configs:
    cm:
        timeout.reconciliation: "30s"
    rbac:
        # Keep RBAC simple for Tier 1; projects gate scope for workloads anyway.
        policy.csv: |
            p, role:read-only, applications, get, */*, allow
            g, system:authenticated, role:read-only
        scopes: "[groups]"